def menu_list():
    print("-------------------------------------------------")
    print("----------   Fleet Control   --------------------")
    print("-------------------------------------------------")
    print("---                                           ---")
    print("---   01 - Adicionar um carro a lista         ---")
    print("---   02 - Adicionar um carro a lista         ---")
    print("---   03 - Adicionar um carro a lista         ---")
    print("---   04 - Adicionar um carro a lista         ---")
    print("---   05 - Adicionar um carro a lista         ---")
    print("---   06 - Adicionar um carro a lista         ---")
    print("---   07 - Adicionar um carro a lista         ---")
    print("---   08 - Adicionar um carro a lista         ---")
    print("---   09 - Adicionar um carro a lista         ---")
    print("---   10 - Adicionar um carro a lista         ---")
    print("---                                           ---")
    print("-------------------------------------------------")